spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    url: jdbc:mariadb://localhost:3307/test_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    password: test
  thymeleaf:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MariaDB102Dialect
    hibernate:
      ddl-auto: update
server:
  port: '80'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
