springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    doc-expansion: none
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
    display-query-params-without-oauth2: 'true'
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  version: '@project.version@'
  paths-to-match: /cart/**, /cartItem/**, /admin/**, /item/**
itemImgLocation: /Users/noel/Documents/github_init/shop-img-resource/
uploadPath: file:///Users/noel/Documents/github_init/shop-img-resource/
spring:
  thymeleaf:
    cache: 'false'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MariaDB102Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: test
    username: test
    url: jdbc:mariadb://localhost:3307/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
  devtools:
    livereload:
      enabled: 'true'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
server:
  port: '80'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
