springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**
spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB102Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: test
    username: test
    url: jdbc:mariadb://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

server:
  port: 80
logging:
  level:
    web: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace